/**
 * The query string as the source of truth for what is on screen.
 *
 * Without it every choice lived in React state: the back gesture on a phone
 * left the app instead of returning to the planner, a refresh or a tab
 * eviction dropped the rider on the welcome screen, and there was nothing to
 * bookmark or send to a friend.
 *
 * The URL describes the visible view only. A mountain link carries the resort
 * and elevation; a planner link carries the view and region. The other half
 * is kept in memory, so switching tabs within a session still returns to the
 * resort you were looking at.
 */

import type { RegionCode } from '@/lib/types';
import { REGIONS } from '@/lib/regions';

export type ViewMode = 'single' | 'compare' | 'planner';
/** A region, the rider's favorites, or the resorts nearest the rider. */
export type ComparisonRegion = RegionCode | 'Favorites' | 'Nearby';
export type Elevation = 'base' | 'summit';

export interface AppUrlState {
  view: ViewMode;
  resortId: string | null;
  elevation: Elevation;
  region: ComparisonRegion;
}

export const DEFAULT_URL_STATE: AppUrlState = {
  view: 'single',
  resortId: null,
  elevation: 'base',
  region: 'us-west',
};

const REGION_CODES = new Set<string>(REGIONS.map((r) => r.code));
// Resort ids are slugs generated by scripts/build-resorts.js. Anything else is
// a hand-edited or truncated link and is dropped rather than looked up.
const RESORT_ID = /^[a-z0-9-]{1,120}$/;

/** Fields a URL actually specified. Absent fields mean "not in this view". */
type ParsedUrl = Pick<AppUrlState, 'view'> & Partial<Omit<AppUrlState, 'view'>>;

function parse(search: string): ParsedUrl {
  const params = new URLSearchParams(search);
  const viewParam = params.get('view');
  const view: ViewMode =
    viewParam === 'compare' || viewParam === 'planner' ? viewParam : 'single';

  if (view === 'single') {
    const resort = params.get('resort');
    return {
      view,
      resortId: resort && RESORT_ID.test(resort) ? resort : null,
      elevation: params.get('elev') === 'summit' ? 'summit' : 'base',
    };
  }

  const regionParam = params.get('region');
  const region: ComparisonRegion | undefined =
    regionParam === 'favorites'
      ? 'Favorites'
      : regionParam === 'nearby'
        ? 'Nearby'
        : regionParam && REGION_CODES.has(regionParam)
          ? (regionParam as RegionCode)
          : undefined;

  return region ? { view, region } : { view };
}

/** Full state from a query string alone, for a first load. */
export function parseUrlState(search: string): AppUrlState {
  return { ...DEFAULT_URL_STATE, ...parse(search) };
}

/**
 * State after navigating to a query string, e.g. on back/forward.
 *
 * Fields the URL is silent on keep their in-memory value, so going back from
 * the planner to a mountain does not forget which region the planner showed.
 */
export function applyUrlState(prev: AppUrlState, search: string): AppUrlState {
  return { ...prev, ...parse(search) };
}

/** Query string for the visible view, with defaults omitted. "" for none. */
export function serializeUrlState(state: AppUrlState): string {
  const params = new URLSearchParams();

  if (state.view === 'single') {
    if (state.resortId) params.set('resort', state.resortId);
    if (state.resortId && state.elevation === 'summit') params.set('elev', 'summit');
  } else {
    params.set('view', state.view);
    // Lowercase slugs for the two pseudo-regions. A shared "nearby" link means
    // near whoever opens it — the sender's location never enters the URL.
    const region =
      state.region === 'Favorites' ? 'favorites' : state.region === 'Nearby' ? 'nearby' : state.region;
    params.set('region', region);
  }

  const query = params.toString();
  return query ? `?${query}` : '';
}
